"use client";

import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import type { AnalysisResult } from "@/types";

interface ExportToolbarProps {
  result: AnalysisResult;
  slug: string | null;
  title: string;
  platform: string;
}

function scoreColor(n: number) {
  if (n >= 80) return "#00aa55";
  if (n >= 60) return "#cc9900";
  return "#cc3333";
}

function grade(n: number) {
  if (n >= 95) return "A+"; if (n >= 87) return "A"; if (n >= 80) return "A-";
  if (n >= 73) return "B+"; if (n >= 67) return "B"; if (n >= 60) return "B-";
  if (n >= 53) return "C+"; if (n >= 47) return "C"; if (n >= 40) return "C-";
  return n >= 20 ? "D" : "F";
}

const DIMS = [
  { key: "healthScore",       label: "Health" },
  { key: "securityScore",     label: "Security" },
  { key: "complexityScore",   label: "Simplicity" },
  { key: "reliabilityScore",  label: "Reliability" },
  { key: "debtScore",         label: "Debt" },
  { key: "memoryScore",       label: "Memory" },
  { key: "resilienceScore",   label: "Resilience" },
  { key: "privacyScore",      label: "Privacy" },
  { key: "aiGuardrailsScore", label: "AI Guardrails" },
];

function triggerDownload(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

function buildMd(result: AnalysisResult, title: string, platform: string): string {
  const s = result.scores as unknown as Record<string, number>;
  const date = new Date().toISOString().slice(0, 10);
  const flags = result.scores.flags;

  const scoreRows = DIMS.map(
    ({ key, label }) => `| ${label} | ${s[key] ?? 0} | ${grade(s[key] ?? 0)} |`
  ).join("\n");

  const flagRows = flags.length
    ? flags.map((f) =>
        `| ${f.severity} | ${f.category} | ${(f.title ?? "").replace(/\|/g, "—")} | ${f.nodeName ?? "—"} | ${f.ptsDeducted ? `−${f.ptsDeducted}` : "—"} |`
      ).join("\n")
    : "| — | — | No flags detected | — | — |";

  const fqi = result.scores.overallScore;

  return [
    `# FlowIntel Analysis Report`,
    ``,
    `**Workflow:** ${title}  `,
    `**Platform:** ${platform}  `,
    `**Nodes:** ${result.parsed.nodeCount}  `,
    `**Date:** ${date}  `,
    `**FQI:** ${fqi} (${grade(fqi)})  `,
    `**Est. Cost/mo:** $${result.scores.estimatedCostUsd.toFixed(2)}`,
    ``,
    `---`,
    ``,
    `## Score Summary`,
    ``,
    `| Dimension | Score | Grade |`,
    `|-----------|------:|-------|`,
    scoreRows,
    ``,
    `---`,
    ``,
    `## Audit Flags (${flags.length} total)`,
    ``,
    `| Severity | Category | Issue | Node | Impact |`,
    `|----------|----------|-------|------|--------|`,
    flagRows,
    ``,
    `---`,
    ``,
    `*Generated by [FlowIntel](https://flowintel.io) — deterministic workflow intelligence.*`,
  ].join("\n");
}

function buildCsv(result: AnalysisResult): string {
  const header = "Severity,Category,Rule,Title,Node,Score Impact\n";
  const rows = result.scores.flags
    .map((f) =>
      [
        f.severity,
        f.category,
        f.rule ?? "",
        `"${(f.title ?? "").replace(/"/g, "'")}"`,
        f.nodeName ?? "",
        f.ptsDeducted ? `-${f.ptsDeducted}` : "",
      ].join(",")
    )
    .join("\n");
  return header + rows;
}

function buildPdfHtml(result: AnalysisResult, title: string, platform: string): string {
  const s = result.scores as unknown as Record<string, number>;
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const fqi = result.scores.overallScore;
  const flags = result.scores.flags;
  const critCount = flags.filter((f) => f.severity === "CRITICAL").length;

  const scoreRows = DIMS.map(({ key, label }) => {
    const val = s[key] ?? 0;
    const color = scoreColor(val);
    const pct = Math.min(val, 100);
    return `
      <tr>
        <td style="padding:8px 12px;font-size:12px;color:#222;border-bottom:1px solid #eee">${label}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #eee">
          <div style="background:#e8e8e8;border-radius:3px;height:8px;width:140px">
            <div style="background:${color};height:8px;border-radius:3px;width:${pct}%"></div>
          </div>
        </td>
        <td style="padding:8px 12px;font-size:13px;font-weight:700;color:${color};border-bottom:1px solid #eee;font-family:monospace">${val}</td>
        <td style="padding:8px 12px;font-size:12px;color:#555;border-bottom:1px solid #eee;font-family:monospace">${grade(val)}</td>
      </tr>`;
  }).join("");

  const flagRows = flags.slice(0, 50).map((f) => {
    const sevColor = f.severity === "CRITICAL" ? "#cc3333" : f.severity === "WARNING" ? "#cc8800" : "#3366cc";
    return `
      <tr>
        <td style="padding:7px 10px;font-size:11px;font-weight:700;color:${sevColor};font-family:monospace;white-space:nowrap">${f.severity}</td>
        <td style="padding:7px 10px;font-size:11px;color:#555">${f.category ?? ""}</td>
        <td style="padding:7px 10px;font-size:11px;color:#222">${(f.title ?? "").replace(/</g, "&lt;")}</td>
        <td style="padding:7px 10px;font-size:11px;color:#888">${f.nodeName ?? "—"}</td>
        <td style="padding:7px 10px;font-size:11px;color:#cc3333;font-family:monospace">${f.ptsDeducted ? `−${f.ptsDeducted}` : "—"}</td>
      </tr>`;
  }).join("");

  const fqiColor = scoreColor(fqi);

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>FlowIntel Report — ${title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;700&family=JetBrains+Mono:wght@400;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; background: #fff; color: #111; padding: 40px; max-width: 900px; margin: 0 auto; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>

<!-- Header -->
<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:32px;padding-bottom:20px;border-bottom:2px solid #111">
  <div>
    <div style="font-family:'JetBrains Mono',monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#888;margin-bottom:6px">FlowIntel Intelligence Report</div>
    <h1 style="font-size:24px;font-weight:300;color:#111;margin-bottom:4px">${title}</h1>
    <div style="font-family:'JetBrains Mono',monospace;font-size:11px;color:#888;letter-spacing:0.1em">
      ${platform} &nbsp;·&nbsp; ${result.parsed.nodeCount} nodes &nbsp;·&nbsp; ${date}
    </div>
  </div>
  <!-- FQI circle -->
  <div style="text-align:center">
    <svg width="90" height="90" viewBox="0 0 90 90">
      <circle cx="45" cy="45" r="36" fill="none" stroke="#eee" stroke-width="8"/>
      <circle cx="45" cy="45" r="36" fill="none" stroke="${fqiColor}" stroke-width="8"
        stroke-linecap="round"
        stroke-dasharray="${(fqi / 100) * 2 * Math.PI * 36} ${2 * Math.PI * 36}"
        stroke-dashoffset="${2 * Math.PI * 36 / 4}"
        transform="rotate(-90 45 45)"/>
      <text x="45" y="40" text-anchor="middle" font-size="20" font-weight="300" fill="#111" font-family="'JetBrains Mono',monospace">${fqi}</text>
      <text x="45" y="56" text-anchor="middle" font-size="10" font-weight="700" fill="${fqiColor}" font-family="'JetBrains Mono',monospace">${grade(fqi)}</text>
    </svg>
    <div style="font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.15em;text-transform:uppercase;color:#888;margin-top:2px">FQI</div>
  </div>
</div>

<!-- Summary chips -->
<div style="display:flex;gap:12px;margin-bottom:28px;flex-wrap:wrap">
  <div style="background:#f5f5f5;border-radius:4px;padding:8px 16px">
    <div style="font-size:10px;color:#888;font-family:'JetBrains Mono',monospace;letter-spacing:0.1em;text-transform:uppercase">Critical Flags</div>
    <div style="font-size:20px;font-weight:700;color:${critCount > 0 ? "#cc3333" : "#00aa55"};font-family:'JetBrains Mono',monospace">${critCount}</div>
  </div>
  <div style="background:#f5f5f5;border-radius:4px;padding:8px 16px">
    <div style="font-size:10px;color:#888;font-family:'JetBrains Mono',monospace;letter-spacing:0.1em;text-transform:uppercase">Total Flags</div>
    <div style="font-size:20px;font-weight:700;color:#111;font-family:'JetBrains Mono',monospace">${flags.length}</div>
  </div>
  <div style="background:#f5f5f5;border-radius:4px;padding:8px 16px">
    <div style="font-size:10px;color:#888;font-family:'JetBrains Mono',monospace;letter-spacing:0.1em;text-transform:uppercase">Est. Cost / mo</div>
    <div style="font-size:20px;font-weight:700;color:#111;font-family:'JetBrains Mono',monospace">$${result.scores.estimatedCostUsd.toFixed(2)}</div>
  </div>
</div>

<!-- Score table -->
<h2 style="font-size:14px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:#333;margin-bottom:12px">Score Breakdown</h2>
<table style="width:100%;border-collapse:collapse;margin-bottom:32px">
  <thead>
    <tr style="background:#f5f5f5">
      <th style="text-align:left;padding:8px 12px;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Dimension</th>
      <th style="text-align:left;padding:8px 12px;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Score</th>
      <th style="text-align:left;padding:8px 12px;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Value</th>
      <th style="text-align:left;padding:8px 12px;font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Grade</th>
    </tr>
  </thead>
  <tbody>${scoreRows}</tbody>
</table>

<!-- Flags table -->
<h2 style="font-size:14px;font-weight:600;letter-spacing:0.08em;text-transform:uppercase;color:#333;margin-bottom:12px">Audit Flags (${flags.length})</h2>
${flags.length === 0
  ? `<p style="font-size:13px;color:#00aa55;padding:16px;background:#f0fff4;border-radius:4px">✓ No flags detected — workflow passed all checks.</p>`
  : `<table style="width:100%;border-collapse:collapse;font-size:12px">
      <thead>
        <tr style="background:#f5f5f5">
          <th style="text-align:left;padding:7px 10px;font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Severity</th>
          <th style="text-align:left;padding:7px 10px;font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Category</th>
          <th style="text-align:left;padding:7px 10px;font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Issue</th>
          <th style="text-align:left;padding:7px 10px;font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Node</th>
          <th style="text-align:left;padding:7px 10px;font-size:10px;letter-spacing:0.08em;text-transform:uppercase;color:#888">Impact</th>
        </tr>
      </thead>
      <tbody>${flagRows}</tbody>
    </table>
    ${flags.length > 50 ? `<p style="font-size:11px;color:#888;margin-top:8px">+ ${flags.length - 50} more flags omitted. View full report online.</p>` : ""}`
}

<!-- Footer -->
<div style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;display:flex;justify-content:space-between;align-items:center">
  <div style="font-family:'JetBrains Mono',monospace;font-size:10px;color:#bbb;letter-spacing:0.1em;text-transform:uppercase">
    FlowIntel · Deterministic Workflow Analysis
  </div>
  <div style="font-family:'JetBrains Mono',monospace;font-size:10px;color:#bbb">
    ${date}
  </div>
</div>

</body>
</html>`;
}

export function ExportToolbar({ result, slug, title, platform }: ExportToolbarProps) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const date = new Date().toISOString().slice(0, 10);
  const safeName = (slug ?? title).replace(/[^a-z0-9-]/gi, "-").toLowerCase();

  const exportMd = () => {
    triggerDownload(buildMd(result, title, platform), `flowintel-${safeName}-${date}.md`, "text/markdown");
  };

  const exportCsv = () => {
    triggerDownload(buildCsv(result), `flowintel-${safeName}-${date}.csv`, "text/csv");
  };

  const exportPdf = async () => {
    setPdfLoading(true);
    try {
      const html = buildPdfHtml(result, title, platform);
      // Open in new tab — user can Ctrl+P / Cmd+P → Save as PDF
      // This avoids any server-side PDF lib dependency
      const win = window.open("", "_blank");
      if (win) {
        win.document.write(html);
        win.document.close();
        // Give fonts a moment to load then trigger print dialog
        setTimeout(() => { win.focus(); win.print(); }, 800);
      }
    } finally {
      setPdfLoading(false);
    }
  };

  const BTN = "flex items-center gap-1.5 px-3 py-1.5 border font-mono text-[10px] uppercase tracking-widest transition-all hover:border-[rgba(0,255,136,0.4)] hover:text-[var(--color-fi-text)]";
  const BTN_STYLE = { borderColor: "rgba(255,255,255,0.14)", color: "var(--color-fi-muted)", background: "rgba(255,255,255,0.02)" };

  return (
    <div className="flex items-center gap-2 flex-wrap">
      <button onClick={exportMd} className={BTN} style={BTN_STYLE}>
        <Download size={11} /> Export .md
      </button>
      <button onClick={exportCsv} className={BTN} style={BTN_STYLE}>
        <Download size={11} /> Export .csv
      </button>
      <button onClick={exportPdf} disabled={pdfLoading} className={BTN} style={BTN_STYLE}>
        {pdfLoading
          ? <><Loader2 size={11} className="animate-spin" /> Preparing…</>
          : <><Download size={11} /> Export PDF</>}
      </button>
    </div>
  );
}
